/**
 * @file src/constants/brand.ts
 * @desc Brand kit data for /brand: core color tokens (hex read from public/brand/packs-palette.json,
 *       generated by @haruhimemoe/brand; tests/unit/constants/brand.test.ts keeps the swatches in
 *       sync with the @haruhimemoe/ui theme at the hue globals.css sets) and the downloadable logo
 *       files in public/brand.
 * @author David @dvhsh (https://dvh.sh)
 * @created Tue Sep 22, 2026
 * @modified Wed Sep 23, 2026
 */

import palette from "../../public/brand/packs-palette.json" with { type: "json" };

/** Swatches shown on /brand, hex sourced from the generated packs-palette.json. */
export const BRAND_COLORS = [
  { token: "b6", name: "Background", hsl: [palette.hue, 10, 10], hex: palette.colors.b6 },
  { token: "b4", name: "Surface", hsl: [palette.hue, 10, 20], hex: palette.colors.b4 },
  { token: "c1", name: "Text", hsl: [palette.hue, 40, 100], hex: palette.colors.c1 },
  { token: "c3", name: "Muted text", hsl: [palette.hue, 40, 80], hex: palette.colors.c3 },
  { token: "h1", name: "Pink", hsl: [palette.hue, 100, 70], hex: palette.colors.h1 },
  { token: "h2", name: "Deep pink", hsl: [palette.hue, 50, 45], hex: palette.colors.h2 },
] as const;

/** Downloadable logo files generated by @haruhimemoe/brand, shown on /brand. */
export const BRAND_ASSETS = [
  { href: "brand/packs-wordmark.svg", label: "wordmark for dark backgrounds", background: "dark" },
  {
    href: "brand/packs-wordmark-on-light.svg",
    label: "wordmark for light backgrounds",
    background: "light",
  },
  { href: "brand/packs-icon.svg", label: "icon", background: "dark" },
] as const;
